In [4]:
import pandas as pd
import numpy as np
from imblearn.over_sampling import RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

from sklearn.linear_model import LogisticRegression 

from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_val_predict

from sklearn.metrics import accuracy_score
from collections import Counter

In [10]:
dataset=pd.read_csv(r"E:\My Work\Top_Dataset\Heart_Dis.csv")

In [12]:
dataset

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

### Check Data is Balanced or Not

In [14]:
dataset["target"].value_counts()

target
1    526
0    499
Name: count, dtype: int64

### Create X and Y Values

In [16]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [18]:
print(x)

[[52.  1.  0. ...  2.  2.  3.]
 [53.  1.  0. ...  0.  0.  3.]
 [70.  1.  0. ...  0.  0.  3.]
 ...
 [47.  1.  0. ...  1.  1.  2.]
 [50.  0.  0. ...  2.  0.  2.]
 [54.  1.  0. ...  1.  1.  3.]]


In [20]:
print(y)

[0 0 0 ... 0 1 0]


### Work on the Data Imbalancing Technique

In [22]:
rm=RandomOverSampler()
x_data,y_data=rm.fit_resample(x,y)

In [24]:
x_data

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [60.,  1.,  0., ...,  2.,  2.,  3.],
       [59.,  1.,  0., ...,  1.,  2.,  1.],
       [55.,  0.,  0., ...,  1.,  0.,  2.]])

In [26]:
y_data

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [32]:
# print("My Acutal Values Before Balancing Data: ",Counter(y))
print("My After Balancing Data: ",Counter(y_data))

My After Balancing Data:  Counter({0: 526, 1: 526})


In [34]:
print(x_data.shape,y_data.shape)

(1052, 13) (1052,)


### 1st Step Define Fold Size with K FOLD Cross Validation Technique

In [36]:
# kf=KFold(n_splits=5,random_state=3, shuffle=True)
# kf.get_n_splits(x)
# print(kf)

KFold(n_splits=5, random_state=3, shuffle=True)


### Define Stratify Fold Size with K FOLD Cross Validation Technique

In [61]:
ksf=StratifiedKFold(n_splits=5,random_state=3, shuffle=True)
ksf.get_n_splits(x_data,y_data)
print(ksf)

StratifiedKFold(n_splits=5, random_state=3, shuffle=True)


In [53]:
from sklearn.linear_model import LogisticRegression
l1=LogisticRegression()

In [55]:
from sklearn.model_selection import train_test_split

In [63]:
for train_data,test_data in ksf.split(x_data,y_data):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]

    score=cross_val_score(l1,x_train,y_train,cv=kf)
    y_pred=cross_val_predict(l1,x_test,y_test,cv=kf)
    
    print("Train : ",y_train.shape," Test: ",y_test.shape)
    print("Train : ",Counter(y_train)," Test: ",Counter(y_test))
    print(score)
    print(y_pred)
    print(np.mean(score)*100)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Train :  (841,)  Test:  (211,)
Train :  Counter({1: 421, 0: 420})  Test:  Counter({0: 106, 1: 105})
[0.81065089 0.83928571 0.86904762 0.78571429 0.85714286]
[0 0 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1
 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 0 1 1 0 1 0 1
 1 1 1 0 0 1 1 0 1 1 0 1 0 0 0 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 0 1 0 1 0 0 1
 0 1 1 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 0 0 0 0 1
 1 0 0 1 1 0 0 1 0 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0
 0 1 1 0 0 1 1 1 0 1 0 0 1 1 1 0 0 1 0 1 1 1 0 0 0 0]
83.23682727528882


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Train :  (841,)  Test:  (211,)
Train :  Counter({0: 421, 1: 420})  Test:  Counter({1: 106, 0: 105})
[0.80473373 0.875      0.82738095 0.8452381  0.82738095]
[0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 0 1 1 0 1 0
 1 1 0 1 0 1 0 0 1 0 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 1 1 0 1 1 1 1 1 0 0 1
 1 0 0 0 0 1 0 1 1 1 0 0 0 1 1 1 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 0 0 0 1 1 1 0 1 1 1 0 1 1 1 0 1 0 0 0 0 0 0 1 1 1 0 1 1 0 0 1 1 0 0 0 0
 1 1 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 0 0
 0 1 1 1 0 1 1 0 1 1 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0]
83.59467455621301


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Train :  (842,)  Test:  (210,)
Train :  Counter({0: 421, 1: 421})  Test:  Counter({0: 105, 1: 105})
[0.85798817 0.82840237 0.79761905 0.8452381  0.81547619]
[0 0 0 1 0 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 1 1 1 1 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 1 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 0 1 0 0 0 1 0 1 0 0
 1 0 0 0 0 1 1 1 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 1 0 1 1 1 1 0 0 1 1 0 1 0
 0 0 0 1 0 0 1 0 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 1 0 1
 1 1 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0
 1 1 1 1 1 0 1 1 0 0 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0]
82.89447731755423


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Train :  (842,)  Test:  (210,)
Train :  Counter({0: 421, 1: 421})  Test:  Counter({0: 105, 1: 105})
[0.87573964 0.84615385 0.86904762 0.8452381  0.83333333]
[0 0 1 1 1 0 1 1 1 1 1 1 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 1 1 1 1 1 0 1 0 0 1
 1 1 0 0 0 0 0 0 1 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0 0 0 0 0 1 0 0 1 1 1 1 1 1
 0 0 1 1 0 1 1 0 1 1 0 1 0 1 1 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 0 1 0 0
 1 1 0 0 1 1 0 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 1 1 1 0 1 0 1 1
 0 1 0 0 0 1 0 0 1 1 1 0 1 1 0 1 0 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 0 1 0 1 1
 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 1 0 0 1 1 1 1]
85.39025077486617


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Train :  (842,)  Test:  (210,)
Train :  Counter({0: 421, 1: 421})  Test:  Counter({0: 105, 1: 105})
[0.81065089 0.84615385 0.875      0.82142857 0.82738095]
[0 0 1 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 0 1 0 1 0 1 1 1 0 1 1 1 1 0 0 1 0 0 0
 1 1 1 1 0 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 0 0 1 1 0 0 0 1 0 0 0 0 1 1 1 1
 1 1 0 0 1 1 1 0 0 1 1 0 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1
 0 0 0 1 0 1 1 1 0 1 1 1 1 1 0 1 0 0 1 1 0 1 0 0 0 1 1 1 1 0 0 1 1 0 0 1 0
 0 1 1 1 1 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 1
 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0]
83.6122851507467


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [19]:
# import numpy as np
# (unique, counts) = np.unique(y_test, return_counts=True)
# frequencies = np.asarray((unique, counts)).T
# print(frequencies)

### Define Logistic Regression

In [20]:
l1=LogisticRegression(random_state=3)

## This is K Fold Cross Validation

In [21]:
# for train_data,test_data in kf.split(x):
#     x_train,x_test=x_data[train_data],x_data[test_data]
#     y_train,y_test=y_data[train_data],y_data[test_data]
#     score=cross_val_score(l1,x_train,y_train,cv=kf)
#     y_pred=cross_val_predict(l1,x_test,y_test,cv=kf)
    

## This is Stratify K Fold Cross Validation

In [23]:
for train_data,test_data in ksf.split(x,y):
    x_train,x_test=x_data[train_data],x_data[test_data]
    y_train,y_test=y_data[train_data],y_data[test_data]
    
    score=cross_val_score(l1,x_train,y_train,cv=ksf)
    y_pred=cross_val_predict(l1,x_test,y_test,cv=ksf)
    
    print("-------My Fold Accuracy Score by Cross Validation Technique-------")
    print(score)
    
    print("**************************************************************")
    print(y_pred)
    print("------------------------------------------------------")
    print("Check Dataset is Balanced")
    import numpy as np
    (unique, counts) = np.unique(y_test, return_counts=True)
    frequencies = np.asarray((unique, counts)).T
    print(frequencies)
    print("--------------------------------------------------------")
    
    from sklearn.metrics import confusion_matrix,accuracy_score
    ac=accuracy_score(y_pred,y_test)*100
    print("Accuracy Score: ",ac)

    print("---------------------------------------------------------")

    cm=confusion_matrix(y_pred,y_test)
    print("This is Confusion Metrics: ")
    print(cm)

    

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.h

-------My Fold Accuracy Score by Cross Validation Technique-------
[0.8597561  0.83536585 0.82317073 0.87195122 0.84756098]
**************************************************************
[0 0 1 1 0 1 0 1 0 1 1 1 1 1 1 1 0 1 1 0 0 1 0 0 0 0 0 1 1 0 1 0 1 1 0 0 1
 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0
 1 0 0 0 0 1 1 0 1 0 1 1 0 1 0 0 0 1 0 1 1 1 1 1 1 0 0 1 0 1 1 1 0 1 0 0 1
 1 0 1 1 0 0 1 1 0 0 0 0 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 0 1 1 0 1 1 0 0 1 0
 0 0 0 1 0 1 1 1 1 0 1 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 0 1 1 1 1 1 0
 1 0 1 0 1 0 0 1 0 1 0 0 1 0 0 0 1 1 0 1]
------------------------------------------------------
Check Dataset is Balanced
[[  0 100]
 [  1 105]]
--------------------------------------------------------
Accuracy Score:  81.95121951219512
---------------------------------------------------------
This is Confusion Metrics: 
[[76 13]
 [24 92]]


C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.h

-------My Fold Accuracy Score by Cross Validation Technique-------
[0.81097561 0.85365854 0.84756098 0.87804878 0.84756098]
**************************************************************
[0 0 1 1 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 0 0 0 0 1 0 0 1 0 0 0 1 1 1 1 1 1 0
 0 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 0 0 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 1
 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 0 0 0 1 0 1 1
 0 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 0 0 1 1 0 1 1 1 1 1 1 0 0 1 1 1 0 0 1 1 0
 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 0 1 0 1 0 1 1 0 0 0 1 1 0 1 0 1 0 1 0 1
 1 1 0 1 1 1 0 1 1 0 1 0 1 0 0 1 0 0 1 0]
------------------------------------------------------
Check Dataset is Balanced
[[  0 100]
 [  1 105]]
--------------------------------------------------------
Accuracy Score:  87.3170731707317
---------------------------------------------------------
This is Confusion Metrics: 
[[83  9]
 [17 96]]


C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.h

-------My Fold Accuracy Score by Cross Validation Technique-------
[0.86585366 0.85365854 0.82926829 0.82926829 0.81097561]
**************************************************************
[0 0 0 0 0 1 1 0 1 0 0 1 0 1 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 0 0 1 1 1 1 1 0
 1 0 1 1 0 1 0 1 0 1 1 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 0 0
 0 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 1 0 1 0 0 1 0 0 1 0 0 1 1 1 1 0 0 1 1 0 1
 0 1 1 1 0 1 1 0 0 0 0 1 0 1 0 1 0 1 1 1 0 0 1 0 0 0 1 0 1 0 1 1 1 1 0 1 1
 1 0 0 1 1 1 1 0 0 0 1 0 0 1 1 1 1 0 0 1 0 0 1 0 1 1 0 1 1 0 0 0 0 0 1 0 1
 1 1 1 0 1 1 1 1 0 1 1 0 0 1 1 1 0 0 0 0]
------------------------------------------------------
Check Dataset is Balanced
[[  0 100]
 [  1 105]]
--------------------------------------------------------
Accuracy Score:  82.92682926829268
---------------------------------------------------------
This is Confusion Metrics: 
[[79 14]
 [21 91]]


C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.h

-------My Fold Accuracy Score by Cross Validation Technique-------
[0.83536585 0.86585366 0.8597561  0.82926829 0.85365854]
**************************************************************
[0 0 1 0 0 0 1 1 0 1 1 0 0 1 1 1 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1 1 1 0 0 0 0
 1 0 1 1 0 1 0 0 1 1 1 1 1 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 1 0
 0 1 0 1 1 1 0 1 1 1 1 0 0 1 0 1 0 0 0 0 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 0
 1 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 0 1 1 1
 1 1 1 0 0 0 0 1 0 0 1 0 1 1 0 1 1 0 1 1 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 0 1
 0 1 0 1 1 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0]
------------------------------------------------------
Check Dataset is Balanced
[[  0 100]
 [  1 105]]
--------------------------------------------------------
Accuracy Score:  80.97560975609757
---------------------------------------------------------
This is Confusion Metrics: 
[[77 16]
 [23 89]]
-------My Fold Accuracy Score by Cross Validation Technique-------
[0.79268293 0.84756098 0.884

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.h

### Stratify Test Case 

In [ ]:
# Test Case 1

# 1 0 0 0 1

# Mejority of Voting wins
# 0 counts= 3
# 1 counts= 2

# 0 is final answer

### Kfold Test Case

In [ ]:
# Test Case 1

# 0 0 1 1 0

# Mejority of Voting wins
# 0 counts= 3
# 1 counts= 2

# 0 is final answer

In [ ]:
# Check Dataset is Balanced
# [[  0 100]
#  [  1 105]]
# --------------------------------------------------------
# Accuracy Score:  81.95121951219512
# ---------------------------------------------------------
# This is Confusion Metrics: 
# [[76 13]
#  [24 92]]


# ***********************
# Check Dataset is Balanced
# [[  0 100]
#  [  1 105]]
# --------------------------------------------------------
# Accuracy Score:  87.3170731707317
# ---------------------------------------------------------
# This is Confusion Metrics: 
# [[82  8]
#  [18 97]]

# ***************************

# Check Dataset is Balanced
# [[  0 100]
#  [  1 105]]
# --------------------------------------------------------
# Accuracy Score:  82.92682926829268
# ---------------------------------------------------------
# This is Confusion Metrics: 
# [[79 14]
#  [21 91]]

# *****************************

# Check Dataset is Balanced
# [[  0 100]
#  [  1 105]]
# --------------------------------------------------------
# Accuracy Score:  80.97560975609757
# ---------------------------------------------------------
# This is Confusion Metrics: 
# [[77 16]
#  [23 89]]

# *******************************

# Check Dataset is Balanced
# [[  0  99]
#  [  1 106]]
# --------------------------------------------------------
# Accuracy Score:  83.41463414634146
# ---------------------------------------------------------
# This is Confusion Metrics: 
# [[82 17]
#  [17 89]]