In [1]:
import numpy as np
import pandas as pd


In [2]:
dataset=pd.read_csv(r"E:\My Work\Top_Dataset\Brain Stroke.csv")
dataset

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [3]:
from sklearn.preprocessing import LabelEncoder
en=LabelEncoder()

In [4]:
dataset["gender"]=en.fit_transform(dataset["gender"])
dataset["ever_married"]=en.fit_transform(dataset["ever_married"])
dataset["work_type"]=en.fit_transform(dataset["work_type"])
dataset["Residence_type"]=en.fit_transform(dataset["Residence_type"])
dataset["smoking_status"]=en.fit_transform(dataset["smoking_status"])

In [5]:
x=dataset.iloc[:,:-1].values # independent 
y=dataset.iloc[:,-1].values  # dependent 

In [6]:
from imblearn.over_sampling import SMOTE
sms=SMOTE()
x_data,y_data=sms.fit_resample(x,y)

In [8]:
# from sklearn.preprocessing import MinMaxScaler
# mms=MinMaxScaler()
# x_scale=mms.fit_transform(x)

In [9]:
# x_scale

In [10]:
# ab1=x_scale.min()
# ab1=round(ab1)
# ab1

In [12]:
# ab2=x_scale.max()
# ab2=round(ab2)
# ab2

In [13]:
from sklearn.preprocessing import RobustScaler
Rb=RobustScaler()
x_robust_scaler=Rb.fit_transform(x_data)

In [14]:
x_robust_scaler

array([[ 0.80623524,  0.23387735,  0.        , ...,  1.97000758,
         1.11196617, -0.49129196],
       [ 0.80623524,  0.62781674,  0.        , ...,  0.13755115,
         0.5200187 ,  0.31711927],
       [-0.19376476, -0.3115772 ,  0.        , ...,  1.11236364,
         0.79433582,  1.12553051],
       ...,
       [-0.19376476,  0.63270575, 14.66772687, ..., -0.30847403,
        -1.09052424,  0.31711927],
       [-0.19376476,  0.48093154, 12.44902306, ..., -0.40727081,
        -0.90831421,  0.31711927],
       [ 0.55071551,  0.48471367,  4.46889282, ...,  0.02552569,
        -0.59792682, -1.09313818]])

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_robust_scaler,y_data,test_size=0.2,random_state=11)


In [29]:
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score

log=LogisticRegression()
log.fit(x_train,y_train)

y_log=log.predict(x_test)
ac_log=accuracy_score(y_log,y_test)*100
ac_log

76.18796198521648

In [31]:
y_log

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [33]:
from sklearn.svm import SVC 
from sklearn.metrics import accuracy_score

sv=SVC()
sv.fit(x_train,y_train)

y_sv=sv.predict(x_test)
ac_sv=accuracy_score(y_sv,y_test)*100
ac_sv

81.25659978880677

In [34]:
y_sv

array([1, 1, 1, ..., 1, 0, 1], dtype=int64)

In [35]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

knn=KNeighborsClassifier()
knn.fit(x_train,y_train)

y_knn=knn.predict(x_test)
ac_knn=accuracy_score(y_knn,y_test)*100
ac_knn

91.4466737064414

In [36]:
y_knn

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [37]:
# Averging
y_all=(ac_log+ac_sv+ac_knn)/3

In [38]:
y_all

82.96374516015489

In [39]:
y_all_pred=(y_log+y_sv+y_knn)/3
y_all_pred

array([1.        , 0.33333333, 1.        , ..., 1.        , 0.        ,
       1.        ])

In [40]:
# Maxvoting Classifier

from sklearn.ensemble import VotingClassifier
max_vote=VotingClassifier(estimators=[('Logistic Regression', log), ('SVM', sv), ('KNN', knn)])
max_vote.fit(x_train,y_train)
max_vote_pred=max_vote.predict(x_test)
max_vote_pred

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [42]:
ac_max_vote=accuracy_score(max_vote_pred,y_test)*100
ac_max_vote

81.57338965153114

In [44]:
# Bagging Classifier
from sklearn.ensemble import BaggingClassifier
bg=BaggingClassifier(estimator=knn,n_estimators=100, random_state=99)
bg.fit(x_train,y_train)

bg_pred=bg.predict(x_test)
bg_pred

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [46]:
ac_bg=accuracy_score(bg_pred,y_test)*100
ac_bg


91.86906019007391

In [52]:
# RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rms=RandomForestClassifier(n_estimators=100)
rms.fit(x_train,y_train)
y_rms=rms.predict(x_test)
y_rms

array([1, 0, 1, ..., 1, 0, 0], dtype=int64)

In [53]:
# [1, 0, 1, ..., 1, 0, 0], ---rms
ac_rms=accuracy_score(y_rms,y_test)*100
ac_rms

96.67370644139388

In [54]:
from sklearn.ensemble import GradientBoostingClassifier
gboost=GradientBoostingClassifier(loss='log_loss', learning_rate=0.1, n_estimators=100)
gboost.fit(x_train,y_train)
y_boost=gboost.predict(x_test)
ac_boost=accuracy_score(y_boost,y_test)*100
ac_boost

95.8817317845829

In [58]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB 217.9 kB/s eta 0:09:34
   ---------------------------------------- 0.0/124.9 MB 196.9 kB/s eta 0:10:35
   ---------------------------------------- 0.1/124.9 MB 353.1 kB/s eta 0:05:54
   ---------------------------------------- 0.1/124.9 MB 525.1 kB/s eta 0:03:58
   ---------------------------------------- 0.2/124.9 MB 546.6 kB/s eta 0:03:49
   ---------------------------------------- 0.3/124.9 MB 714.4 kB/s eta 0:02:55
   ---------------------------------------- 0.4/124.9 MB 942.8 kB/s eta 0:02:13
   ---------------------------------------- 0.5/124.9 MB 1.2 MB/s eta 0:01:47


In [ ]:
# Regulerization - L1 and l2 

In [64]:
from xgboost import XGBClassifier
model=XGBClassifier()
model.fit(x_train,y_train)

model_pred=model.predict(x_test)
ac_model=accuracy_score(model_pred,y_test)*100
ac_model

96.19852164730729